### ISSUE TITLE
Should have a default grid size

### ISSUE THREAD

**Issue by ShayBox** [Malpp/DiscordGifSplitter#3]
Emojis are default 32x32 unless there are I believe 27 of them, or there's also text in the message in which case its 22x22, grids should be set to 32x32 by default and decreased to 22x22 if there are more than 27 emojis to optimize quality per gif.

**Comment by Malpp** [comment]
Alright, I confirmed the emote size is 22x22 and it changes when there are 27 of them according to [this](https://support.discordapp.com/hc/en-us/articles/207619737-Adding-Emoji-Magic) too.

**Comment by Malpp** [comment]
![btxysmbykn](https://user-images.githubusercontent.com/17149559/50458062-58888b80-092e-11e9-9641-a07e12d1fc70.gif)
